import SetInitialValueReduxState from "@/ClientFiles/Components/Root/SetInitialValueReduxState";
import StoreProvider from "@/ClientFiles/StoreProvider/StoreProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/ClientFiles/Components/Shared/Navbar/Navbar";
import Footer from "@/ClientFiles/Components/Shared/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="/images/logo.png" type="image/x-icon" />
      </head>
      <body
        id="root"
        className={inter.className}
        style={{ backgroundColor: "var(--primary)" }}
      >
        <StoreProvider>
          <SetInitialValueReduxState>
            <Navbar />
            {children}
            <Footer />
          </SetInitialValueReduxState>
        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
